# Generated by Django 2.0.8 on 2018-12-18 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vapyr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointable',
            name='gameKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='vapyr_app.Game'),
        ),
        migrations.AlterField(
            model_name='jointable',
            name='userKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='vapyr_app.UserProfile'),
        ),
    ]
