# Generated by Django 2.0.8 on 2018-12-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapyr_app', '0003_auto_20181220_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pref_plat_id',
            field=models.CharField(default=146, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pref_platform',
            field=models.CharField(choices=[('PS4', 'PS4'), ('SWITCH', 'Nintendo Switch'), ('XBOXONE', 'Xbox One'), ('PC', 'PC')], default='PS4', max_length=100),
        ),
    ]
